### ISSUE TITLE
AttributeError from `get_version()` call

### ISSUE THREAD

**Issue by HenryDane** [CADWRDeltaModeling/pyhecdss#4]
Calling `get_version()` from an otherwise fine DSS File object will throw the following error (but will leave the object in a valid state):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "{....}\pyhecdss\pyhecdss.py", line 39, in get_version
    pyheclib.zfver_(self.fname, char *cver, int *iver, len(fname), len(cver));
AttributeError: module 'pyhecdss.pyheclib' has no attribute 'zfver_'
```

**Comment by dwr-psandhu** [comment]
Will implement in the next version. Thanks
